USE [SMS]
GO

-- 删除用户
DROP USER [User_3005]
DROP USER [User_3006]
DROP USER [User_3007]
DROP USER [User_3008]
DROP USER [User_3009]
DROP USER [User_3010]
DROP USER [User_3013]


-- 3. 设置用户对应默认Schema
CREATE USER User_3005 FOR LOGIN User_3005 WITH DEFAULT_SCHEMA = SBIPlant
CREATE USER User_3006 FOR LOGIN User_3006 WITH DEFAULT_SCHEMA = SBIPlant
CREATE USER User_3007 FOR LOGIN User_3007 WITH DEFAULT_SCHEMA = SBIPlant
CREATE USER User_3008 FOR LOGIN User_3008 WITH DEFAULT_SCHEMA = SBIPlant
CREATE USER User_3009 FOR LOGIN User_3009 WITH DEFAULT_SCHEMA = SBIPlant
CREATE USER User_3010 FOR LOGIN User_3010 WITH DEFAULT_SCHEMA = SBIPlant
CREATE USER User_3013 FOR LOGIN User_3013 WITH DEFAULT_SCHEMA = SBIPlant

GO

-- 4. 设置权限
GRANT INSERT, SELECT, UPDATE, DELETE, EXECUTE, REFERENCES ON SCHEMA:: SBIPlant TO User_3005
GRANT INSERT, SELECT, UPDATE, DELETE, EXECUTE, REFERENCES ON SCHEMA:: SBIPlant TO User_3006
GRANT INSERT, SELECT, UPDATE, DELETE, EXECUTE, REFERENCES ON SCHEMA:: SBIPlant TO User_3007
GRANT INSERT, SELECT, UPDATE, DELETE, EXECUTE, REFERENCES ON SCHEMA:: SBIPlant TO User_3008
GRANT INSERT, SELECT, UPDATE, DELETE, EXECUTE, REFERENCES ON SCHEMA:: SBIPlant TO User_3009
GRANT INSERT, SELECT, UPDATE, DELETE, EXECUTE, REFERENCES ON SCHEMA:: SBIPlant TO User_3010
GRANT INSERT, SELECT, UPDATE, DELETE, EXECUTE, REFERENCES ON SCHEMA:: SBIPlant TO User_3013
