/*

  -- 1. 创建Schema
  -- 2. 创建登录用户
  -- 3. 设置用户对应默认Schema
  -- 4. 设置权限
  -- 5. 创建函数(根据登录用户获取厂房编码)
  -- 6. sqlsearch Database查找.dbo.
  
*/

-- 1. 创建Schema
CREATE SCHEMA SBIPlant AUTHORIZATION dbo
GO


-- 2.创建登录用户
CREATE LOGIN User_3005 WITH PASSWORD = N'123456'
CREATE LOGIN User_3006 WITH PASSWORD = N'123456'
CREATE LOGIN User_3007 WITH PASSWORD = N'123456'
CREATE LOGIN User_3008 WITH PASSWORD = N'123456'
CREATE LOGIN User_3009 WITH PASSWORD = N'123456'
CREATE LOGIN User_3010 WITH PASSWORD = N'123456'
CREATE LOGIN User_3013 WITH PASSWORD = N'123456'

GO

-- 3. 设置用户对应默认Schema
CREATE USER User_3005 FOR LOGIN User_3005 WITH DEFAULT_SCHEMA = SBIPlant
CREATE USER User_3006 FOR LOGIN User_3006 WITH DEFAULT_SCHEMA = SBIPlant
CREATE USER User_3007 FOR LOGIN User_3007 WITH DEFAULT_SCHEMA = SBIPlant
CREATE USER User_3008 FOR LOGIN User_3008 WITH DEFAULT_SCHEMA = SBIPlant
CREATE USER User_3009 FOR LOGIN User_3009 WITH DEFAULT_SCHEMA = SBIPlant
CREATE USER User_3010 FOR LOGIN User_3010 WITH DEFAULT_SCHEMA = SBIPlant
CREATE USER User_3013 FOR LOGIN User_3013 WITH DEFAULT_SCHEMA = SBIPlant

GO

-- 4. 设置权限
GRANT INSERT, SELECT, UPDATE, DELETE, EXECUTE, REFERENCES ON SCHEMA:: SBIPlant TO User_3005
GRANT INSERT, SELECT, UPDATE, DELETE, EXECUTE, REFERENCES ON SCHEMA:: SBIPlant TO User_3006
GRANT INSERT, SELECT, UPDATE, DELETE, EXECUTE, REFERENCES ON SCHEMA:: SBIPlant TO User_3007
GRANT INSERT, SELECT, UPDATE, DELETE, EXECUTE, REFERENCES ON SCHEMA:: SBIPlant TO User_3008
GRANT INSERT, SELECT, UPDATE, DELETE, EXECUTE, REFERENCES ON SCHEMA:: SBIPlant TO User_3009
GRANT INSERT, SELECT, UPDATE, DELETE, EXECUTE, REFERENCES ON SCHEMA:: SBIPlant TO User_3010
GRANT INSERT, SELECT, UPDATE, DELETE, EXECUTE, REFERENCES ON SCHEMA:: SBIPlant TO User_3013

GO


-- 5. 创建函数(根据登录用户获取厂房编码)
CREATE FUNCTION [SBIPlant].[F_GetCompanyCode] ()
RETURNS varchar(4)
WITH SCHEMABINDING, EXEC AS CALLER
AS
BEGIN
DECLARE @strCompanyCode VARCHAR(4);
      SET @strCompanyCode =
             CASE
                WHEN (LEFT(RIGHT(USER_NAME(),4),1) = '3')
                THEN
                   CONVERT (VARCHAR, RIGHT(USER_NAME(),4))
                ELSE
                   NULL
             END
      RETURN @strCompanyCode;
END
GO
